import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { type ChatCompletionRequestMessage } from "openai";

// # Dummy conversation
const conversation: ChatCompletionRequestMessage[] = [
  { role: "user", content: "Hi, I'm planning a trip to Europe." },
  {
    role: "assistant",
    content:
      "Great! I can help with that. Where in Europe are you planning to go?",
  },
  {
    role: "user",
    content: "I'm thinking of visiting Paris, Rome, and Barcelona.",
  },
  {
    role: "assistant",
    content: "Sounds like a fantastic trip! When are you planning to go?",
  },
  {
    role: "user",
    content: "I'm planning to go in the summer, around August.",
  },
  {
    role: "assistant",
    content:
      "That's a popular time to visit Europe. How long will you be staying?",
  },
  {
    role: "user",
    content: "I'm planning to stay for three weeks.",
  },
  {
    role: "assistant",
    content:
      "Three weeks should give you enough time to explore these cities thoroughly. Do you need help with booking flights or accommodations?",
  },
  {
    role: "user",
    content:
      "Yes, I would appreciate some recommendations for affordable accommodations.",
  },
  {
    role: "assistant",
    content:
      "Sure! For Paris, you can consider staying in budget hotels like Ibis or Holiday Inn Express. In Rome, budget options like Hotel Artemide or Hotel Quirinale are good choices. And in Barcelona, you can check out Hotel Acta Antibes or Hotel Ronda House. Would you like me to help with booking?",
  },
  {
    role: "user",
    content:
      "Yes, please! Can you find me the best deals for flights from my location to these cities?",
  },
  {
    role: "assistant",
    content:
      "Sure! Can you please provide me with your current location and travel dates? I'll find the best flight options for you.",
  },
  // ... continue with more conversation messages
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-800">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Chat with me!
          </h1>
          <div className="min-h-full max-w-xl divide-y-4 divide-slate-800 bg-white">
            {conversation.map((c, i) => (
              <ConversationBox conversation={c} key={i} />
            ))}
            <UserInputBox />
          </div>
        </div>
      </main>
    </>
  );
};

const ConversationBox: React.FC<{
  conversation: ChatCompletionRequestMessage;
}> = ({ conversation }) => {
  return (
    <div className="flex gap-4 p-3">
      {/* profile pic */}
      <div className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-500 p-6">
        <div>
          {conversation.role === "user" ? (
            <UserIcon></UserIcon>
          ) : (
            <AssistantIcon />
          )}
        </div>
      </div>
      <div className="">
        <p className="italic text-slate-600">{conversation.role}</p>
        <p>{conversation.content}</p>
      </div>
    </div>
  );
};

const UserInputBox: React.FC = () => {
  return (
    <div className="flex items-center bg-slate-300">
      {/* User Input */}
      <textarea className="m-3 w-9/12 p-3"></textarea>
      <div className="m-3 flex h-10 w-10 items-center justify-center rounded-full bg-slate-500 p-6">
        <div>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="white"
            className="h-6 w-6"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3"
            />
          </svg>
        </div>
      </div>
    </div>
  );
};

const UserIcon: React.FC = () => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      strokeWidth={1.5}
      stroke="white"
      className="h-6 w-6"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z"
      />
    </svg>
  );
};
const AssistantIcon: React.FC = () => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      strokeWidth={1.5}
      stroke="white"
      className="h-6 w-6"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M8.25 3v1.5M4.5 8.25H3m18 0h-1.5M4.5 12H3m18 0h-1.5m-15 3.75H3m18 0h-1.5M8.25 19.5V21M12 3v1.5m0 15V21m3.75-18v1.5m0 15V21m-9-1.5h10.5a2.25 2.25 0 002.25-2.25V6.75a2.25 2.25 0 00-2.25-2.25H6.75A2.25 2.25 0 004.5 6.75v10.5a2.25 2.25 0 002.25 2.25zm.75-12h9v9h-9v-9z"
      />
    </svg>
  );
};
export default Home;
